/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Locked */
                423: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MeResponse"];
                        "application/json": components["schemas"]["MeResponse"];
                        "text/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerSummary"][];
                        "application/json": components["schemas"]["CustomerSummary"][];
                        "text/json": components["schemas"]["CustomerSummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveCustomerRequest"];
                    "text/json": components["schemas"]["SaveCustomerRequest"];
                    "application/*+json": components["schemas"]["SaveCustomerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateCustomerResponse"];
                        "application/json": components["schemas"]["CreateCustomerResponse"];
                        "text/json": components["schemas"]["CreateCustomerResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/profit-percents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfitPercentDto"][];
                        "application/json": components["schemas"]["ProfitPercentDto"][];
                        "text/json": components["schemas"]["ProfitPercentDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerSummary"];
                        "application/json": components["schemas"]["CustomerSummary"];
                        "text/json": components["schemas"]["CustomerSummary"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveCustomerRequest"];
                    "text/json": components["schemas"]["SaveCustomerRequest"];
                    "application/*+json": components["schemas"]["SaveCustomerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/records/{entityType}/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    entityType: string;
                    entityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RecordHistoryResponse"];
                        "application/json": components["schemas"]["RecordHistoryResponse"];
                        "text/json": components["schemas"]["RecordHistoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/documents/{docType}/{docId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    docType: string;
                    docId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DocumentVersionSummary"][];
                        "application/json": components["schemas"]["DocumentVersionSummary"][];
                        "text/json": components["schemas"]["DocumentVersionSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/documents/{docType}/{docId}/versions/{versionNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    docType: string;
                    docId: number;
                    versionNo: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DocumentVersionDetail"];
                        "application/json": components["schemas"]["DocumentVersionDetail"];
                        "text/json": components["schemas"]["DocumentVersionDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ItemSummary"][];
                        "application/json": components["schemas"]["ItemSummary"][];
                        "text/json": components["schemas"]["ItemSummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveItemRequest"];
                    "text/json": components["schemas"]["SaveItemRequest"];
                    "application/*+json": components["schemas"]["SaveItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateItemResponse"];
                        "application/json": components["schemas"]["CreateItemResponse"];
                        "text/json": components["schemas"]["CreateItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ItemSummary"];
                        "application/json": components["schemas"]["ItemSummary"];
                        "text/json": components["schemas"]["ItemSummary"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveItemRequest"];
                    "text/json": components["schemas"]["SaveItemRequest"];
                    "application/*+json": components["schemas"]["SaveItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ItemStockResponse"];
                        "application/json": components["schemas"]["ItemStockResponse"];
                        "text/json": components["schemas"]["ItemStockResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}/stock/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateStockAdjustmentRequest"];
                    "text/json": components["schemas"]["CreateStockAdjustmentRequest"];
                    "application/*+json": components["schemas"]["CreateStockAdjustmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/numbering": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DocumentSeriesDto"][];
                        "application/json": components["schemas"]["DocumentSeriesDto"][];
                        "text/json": components["schemas"]["DocumentSeriesDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/numbering/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveDocumentSeriesRequest"];
                    "text/json": components["schemas"]["SaveDocumentSeriesRequest"];
                    "application/*+json": components["schemas"]["SaveDocumentSeriesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/numbering/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PreviewNumberRequest"];
                    "text/json": components["schemas"]["PreviewNumberRequest"];
                    "application/*+json": components["schemas"]["PreviewNumberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NumberPreview"];
                        "application/json": components["schemas"]["NumberPreview"];
                        "text/json": components["schemas"]["NumberPreview"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/numbering/initialise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    apply?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesInitialisation"][];
                        "application/json": components["schemas"]["SeriesInitialisation"][];
                        "text/json": components["schemas"]["SeriesInitialisation"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleSummary"][];
                        "application/json": components["schemas"]["RoleSummary"][];
                        "text/json": components["schemas"]["RoleSummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveRoleRequest"];
                    "text/json": components["schemas"]["SaveRoleRequest"];
                    "application/*+json": components["schemas"]["SaveRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleSummary"];
                        "application/json": components["schemas"]["RoleSummary"];
                        "text/json": components["schemas"]["RoleSummary"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PermissionCatalogueEntry"][];
                        "application/json": components["schemas"]["PermissionCatalogueEntry"][];
                        "text/json": components["schemas"]["PermissionCatalogueEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveRoleRequest"];
                    "text/json": components["schemas"]["SaveRoleRequest"];
                    "application/*+json": components["schemas"]["SaveRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanySummary"][];
                        "application/json": components["schemas"]["CompanySummary"][];
                        "text/json": components["schemas"]["CompanySummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyProfile"];
                        "application/json": components["schemas"]["CompanyProfile"];
                        "text/json": components["schemas"]["CompanyProfile"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompanyProfile"];
                    "text/json": components["schemas"]["CompanyProfile"];
                    "application/*+json": components["schemas"]["CompanyProfile"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyProfile"];
                        "application/json": components["schemas"]["CompanyProfile"];
                        "text/json": components["schemas"]["CompanyProfile"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/business-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusinessRule"][];
                        "application/json": components["schemas"]["BusinessRule"][];
                        "text/json": components["schemas"]["BusinessRule"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BusinessRule"][];
                    "text/json": components["schemas"]["BusinessRule"][];
                    "application/*+json": components["schemas"]["BusinessRule"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/tax-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaxRateDto"][];
                        "application/json": components["schemas"]["TaxRateDto"][];
                        "text/json": components["schemas"]["TaxRateDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveTaxRateRequest"];
                    "text/json": components["schemas"]["SaveTaxRateRequest"];
                    "application/*+json": components["schemas"]["SaveTaxRateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaxRateDto"];
                        "application/json": components["schemas"]["TaxRateDto"];
                        "text/json": components["schemas"]["TaxRateDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/tax-rates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveTaxRateRequest"];
                    "text/json": components["schemas"]["SaveTaxRateRequest"];
                    "application/*+json": components["schemas"]["SaveTaxRateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/mail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MailSettingsResponse"];
                        "application/json": components["schemas"]["MailSettingsResponse"];
                        "text/json": components["schemas"]["MailSettingsResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveMailSettingsRequest"];
                    "text/json": components["schemas"]["SaveMailSettingsRequest"];
                    "application/*+json": components["schemas"]["SaveMailSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/mail/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SendTestEmailRequest"];
                    "text/json": components["schemas"]["SendTestEmailRequest"];
                    "application/*+json": components["schemas"]["SendTestEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/email-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmailTemplateDto"][];
                        "application/json": components["schemas"]["EmailTemplateDto"][];
                        "text/json": components["schemas"]["EmailTemplateDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/email-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveEmailTemplateRequest"];
                    "text/json": components["schemas"]["SaveEmailTemplateRequest"];
                    "application/*+json": components["schemas"]["SaveEmailTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SupplierSummary"][];
                        "application/json": components["schemas"]["SupplierSummary"][];
                        "text/json": components["schemas"]["SupplierSummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveSupplierRequest"];
                    "text/json": components["schemas"]["SaveSupplierRequest"];
                    "application/*+json": components["schemas"]["SaveSupplierRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateSupplierResponse"];
                        "application/json": components["schemas"]["CreateSupplierResponse"];
                        "text/json": components["schemas"]["CreateSupplierResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SupplierSummary"];
                        "application/json": components["schemas"]["SupplierSummary"];
                        "text/json": components["schemas"]["SupplierSummary"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveSupplierRequest"];
                    "text/json": components["schemas"]["SaveSupplierRequest"];
                    "application/*+json": components["schemas"]["SaveSupplierRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserSummary"][];
                        "application/json": components["schemas"]["UserSummary"][];
                        "text/json": components["schemas"]["UserSummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                    "text/json": components["schemas"]["CreateUserRequest"];
                    "application/*+json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateUserResponse"];
                        "application/json": components["schemas"]["CreateUserResponse"];
                        "text/json": components["schemas"]["CreateUserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserSummary"];
                        "application/json": components["schemas"]["UserSummary"];
                        "text/json": components["schemas"]["UserSummary"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                    "text/json": components["schemas"]["UpdateUserRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResetPasswordResponse"];
                        "application/json": components["schemas"]["ResetPasswordResponse"];
                        "text/json": components["schemas"]["ResetPasswordResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetOverrideRequest"];
                    "text/json": components["schemas"]["SetOverrideRequest"];
                    "application/*+json": components["schemas"]["SetOverrideRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetUserPermissionsRequest"];
                    "text/json": components["schemas"]["SetUserPermissionsRequest"];
                    "application/*+json": components["schemas"]["SetUserPermissionsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditEntry: {
            /** Format: int64 */
            id: number;
            entityType: string;
            entityId: string;
            action: string;
            /** Format: int64 */
            changedBy?: number | null;
            changedByName?: string | null;
            /** Format: date-time */
            changedAt: string;
            reason?: string | null;
            changes?: string | null;
            ipAddress?: string | null;
            correlationId?: string | null;
        };
        BusinessRule: {
            key: string;
            value: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CompanyProfile: {
            /** Format: int64 */
            id: number;
            name: string;
            isVatRegistered: boolean;
            vatNumber?: string | null;
            addressLine1?: string | null;
            addressLine2?: string | null;
            city?: string | null;
            country?: string | null;
            phone?: string | null;
            email?: string | null;
            website?: string | null;
            bankName?: string | null;
            bankBranch?: string | null;
            bankAccountName?: string | null;
            bankAccountNumber?: string | null;
            brandColour?: string | null;
        };
        CompanySummary: {
            /** Format: int64 */
            id: number;
            name: string;
            isVatRegistered: boolean;
        };
        CreateCustomerResponse: {
            /** Format: int64 */
            id: number;
            code: string;
        };
        CreateItemResponse: {
            /** Format: int64 */
            id: number;
            code: string;
        };
        CreateStockAdjustmentRequest: {
            /** Format: double */
            quantity: number;
            reason: string;
            /** Format: date-time */
            occurredAt?: string | null;
        };
        CreateSupplierResponse: {
            /** Format: int64 */
            id: number;
            code: string;
        };
        CreateUserRequest: {
            username: string;
            name: string;
            roleIds: number[];
        };
        CreateUserResponse: {
            /** Format: int64 */
            id: number;
            temporaryPassword: string;
        };
        CustomerSummary: {
            /** Format: int64 */
            id: number;
            code: string;
            name: string;
            type?: string | null;
            contactPerson?: string | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            vatNumber?: string | null;
            /** Format: int64 */
            assignedCompanyId?: number | null;
            /** Format: int64 */
            profitPercentId?: number | null;
            /** Format: double */
            creditLimit: number;
        };
        DocumentSeriesDto: {
            /** Format: int64 */
            id: number;
            docType: string;
            prefix: string;
            /** Format: int64 */
            nextNumber: number;
            /** Format: int32 */
            padding: number;
            example: string;
        };
        DocumentVersionDetail: {
            /** Format: int64 */
            id: number;
            docType: string;
            /** Format: int64 */
            docId: number;
            /** Format: int32 */
            versionNo: number;
            /** Format: int64 */
            changedBy?: number | null;
            changedByName?: string | null;
            /** Format: date-time */
            changedAt: string;
            reason?: string | null;
            snapshot: string;
        };
        DocumentVersionSummary: {
            /** Format: int64 */
            id: number;
            docType: string;
            /** Format: int64 */
            docId: number;
            /** Format: int32 */
            versionNo: number;
            /** Format: int64 */
            changedBy?: number | null;
            changedByName?: string | null;
            /** Format: date-time */
            changedAt: string;
            reason?: string | null;
        };
        EmailTemplateDto: {
            /** Format: int64 */
            id: number;
            templateKey: string;
            subject: string;
            body: string;
        };
        ItemStockResponse: {
            /** Format: int64 */
            itemId: number;
            code: string;
            name: string;
            /** Format: double */
            reorderLevel?: number | null;
            /** Format: double */
            balance: number;
            movements: components["schemas"]["StockMovementDto"][];
            batches: components["schemas"]["StockBatchDto"][];
        };
        ItemSummary: {
            /** Format: int64 */
            id: number;
            code: string;
            name: string;
            /** Format: double */
            sellingPrice?: number | null;
            /** Format: double */
            cost?: number | null;
            /** Format: double */
            reorderLevel?: number | null;
            unit?: string | null;
            /** Format: double */
            stockBalance: number;
            belowReorder: boolean;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            /** Format: int64 */
            userId: number;
            username: string;
            name: string;
            mustChangePassword: boolean;
            permissions: string[];
            /** Format: date-time */
            expiresAt: string;
        };
        MailSettingsResponse: {
            host: string;
            /** Format: int32 */
            port: number;
            useSsl: boolean;
            username?: string | null;
            hasPassword: boolean;
            fromAddress?: string | null;
            fromName?: string | null;
            replyTo?: string | null;
            bcc?: string | null;
            sendEnabled: boolean;
            /** Format: int32 */
            dailyLimit: number;
        };
        MeResponse: {
            /** Format: int64 */
            userId: number;
            username: string;
            mustChangePassword: boolean;
            permissions: string[];
        };
        NumberPreview: {
            now: string;
            nextMonth: string;
        };
        PermissionCatalogueEntry: {
            key: string;
            isLegacy: boolean;
        };
        PreviewNumberRequest: {
            prefix: string;
            /** Format: int64 */
            nextNumber: number;
            /** Format: int32 */
            padding: number;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        ProfitPercentDto: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        RecordHistoryResponse: {
            entries: components["schemas"]["AuditEntry"][];
            /** Format: int32 */
            total: number;
        };
        ResetPasswordResponse: {
            temporaryPassword: string;
        };
        RoleSummary: {
            /** Format: int64 */
            id: number;
            name: string;
            description?: string | null;
            isSystem: boolean;
            /** Format: int64 */
            companyId?: number | null;
            permissions: string[];
        };
        SaveCustomerRequest: {
            name: string;
            type?: string | null;
            contactPerson?: string | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            vatNumber?: string | null;
            /** Format: int64 */
            assignedCompanyId?: number | null;
            /** Format: int64 */
            profitPercentId?: number | null;
            /** Format: double */
            creditLimit: number;
        };
        SaveDocumentSeriesRequest: {
            prefix: string;
            /** Format: int32 */
            padding: number;
        };
        SaveEmailTemplateRequest: {
            subject: string;
            body: string;
        };
        SaveItemRequest: {
            name: string;
            /** Format: double */
            sellingPrice?: number | null;
            /** Format: double */
            cost?: number | null;
            /** Format: double */
            reorderLevel?: number | null;
            unit?: string | null;
        };
        SaveMailSettingsRequest: {
            host: string;
            /** Format: int32 */
            port: number;
            useSsl: boolean;
            username?: string | null;
            password?: string | null;
            fromAddress?: string | null;
            fromName?: string | null;
            replyTo?: string | null;
            bcc?: string | null;
            sendEnabled: boolean;
            /** Format: int32 */
            dailyLimit: number;
        };
        SaveRoleRequest: {
            name: string;
            description?: string | null;
            /** Format: int64 */
            companyId?: number | null;
            permissions: string[];
        };
        SaveSupplierRequest: {
            name: string;
            contactPerson?: string | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            vatNumber?: string | null;
        };
        SaveTaxRateRequest: {
            name: string;
            /** Format: double */
            percentage: number;
            /** Format: date */
            effectiveFrom: string;
            /** Format: date */
            effectiveTo?: string | null;
            isDefault: boolean;
        };
        SendTestEmailRequest: {
            to: string;
        };
        SeriesInitialisation: {
            /** Format: int64 */
            companyId: number;
            docType: string;
            observedPrefix: string;
            prefix: string;
            example: string;
            /** Format: int64 */
            lastIssued?: number | null;
            /** Format: int64 */
            nextNumber: number;
            source: string;
        };
        SetOverrideRequest: {
            permission: string;
            granted?: boolean | null;
        };
        SetUserPermissionsRequest: {
            permissions: string[];
        };
        StockBatchDto: {
            /** Format: int64 */
            id: number;
            /** Format: double */
            quantity?: number | null;
            /** Format: double */
            balance?: number | null;
            /** Format: double */
            unitCost?: number | null;
            /** Format: date */
            inDate?: string | null;
            enteredBy?: string | null;
        };
        StockMovementDto: {
            /** Format: int64 */
            id: number;
            type: string;
            /** Format: double */
            quantity: number;
            /** Format: double */
            balanceAfter: number;
            reason?: string | null;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            createdBy?: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        SupplierSummary: {
            /** Format: int64 */
            id: number;
            code: string;
            name: string;
            contactPerson?: string | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            vatNumber?: string | null;
        };
        TaxRateDto: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: double */
            percentage: number;
            /** Format: date */
            effectiveFrom: string;
            /** Format: date */
            effectiveTo?: string | null;
            isDefault: boolean;
        };
        UpdateUserRequest: {
            name: string;
            roleIds: number[];
        };
        UserSummary: {
            /** Format: int64 */
            id: number;
            username: string;
            name: string;
            isDisabled: boolean;
            mustChangePassword: boolean;
            isLockedOut: boolean;
            roles: components["schemas"]["RoleSummary"][];
            effectivePermissions: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
