"use client";

import {
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable,
  type ColumnDef,
  type SortingState,
} from "@tanstack/react-table";
import {
  ArrowDown,
  ArrowUp,
  ChevronLeft,
  ChevronRight,
  Download,
  Inbox,
  Search,
} from "lucide-react";
import { useState, type ReactNode } from "react";
import { cn } from "@/lib/cn";
import { Button, Input, Skeleton, toast } from "@/components/ui";
import { downloadExcel } from "./export";

/**
 * The list, for every list in the application.
 *
 * The legacy app has 44 controllers and a hand-rolled grid in most of them, which is why a bug fixed
 * on one screen survives on the other forty-three, and why "add a column" is a day's work in six
 * places. The entire point of this component is that the next screen is a column definition and a
 * query, and nothing else.
 *
 * Sorting, filtering, pagination and export are all client-side, which is right for the data volumes
 * here (2,485 invoices is nothing) and wrong the moment a list is genuinely large. When that happens
 * — Phase 5 — this grows server-side modes; the call sites should not have to change.
 */
export interface DataTableProps<T> {
  columns: ColumnDef<T, unknown>[];
  rows: T[] | undefined;

  /** True while the first load is in flight. Renders a skeleton shaped like the table. */
  loading?: boolean;

  /** What the user searches. Given a row, return the text that should match. */
  searchable?: (row: T) => string;
  searchPlaceholder?: string;

  /**
   * Enables the export button: a real .xlsx, generated by the server.
   *
   * The server writes money as a numeric cell from the `decimal` it already holds. A spreadsheet
   * built in the browser would be re-parsing strings, and a money column that lands in Excel as text
   * cannot be summed — which is the first thing anyone does with an exported list.
   */
  exportUrl?: string;

  /** Filename for the download. Defaults to the sheet name plus today's date, set by the server. */
  exportFilename?: string;

  /** Shown when there is genuinely nothing — not while loading, and not when a filter hid it all. */
  empty?: { title: string; description?: string; action?: ReactNode };

  onRowClick?: (row: T) => void;

  pageSize?: number;

  /**
   * The column the list is sorted by when it first loads, and its direction.
   *
   * Without this a list renders in whatever order the API returned, which reads as jumbled the
   * moment two people expect two different orders. A default here means the list is always sorted by
   * *something* visible — the header shows the arrow — and the user can still click to re-sort.
   */
  defaultSort?: { id: string; desc?: boolean };
}

export function DataTable<T>({
  columns,
  rows,
  loading,
  searchable,
  searchPlaceholder = "Search…",
  exportUrl,
  exportFilename = "export.xlsx",
  empty,
  onRowClick,
  pageSize = 25,
  defaultSort,
}: DataTableProps<T>) {
  const [sorting, setSorting] = useState<SortingState>(
    defaultSort ? [{ id: defaultSort.id, desc: defaultSort.desc ?? false }] : [],
  );
  const [query, setQuery] = useState("");
  const [exporting, setExporting] = useState(false);

  const table = useReactTable({
    data: rows ?? [],
    columns,
    state: { sorting, globalFilter: query },
    onSortingChange: setSorting,
    onGlobalFilterChange: setQuery,

    // Searching a row means searching what the user can SEE, not the raw object — an id, a
    // timestamp and a permission key are all in the row and none of them are what someone typing
    // "kandy" is looking for.
    globalFilterFn: searchable
      ? (row, _columnId, value) =>
          searchable(row.original).toLowerCase().includes(String(value).toLowerCase())
      : "includesString",

    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),

    initialState: { pagination: { pageSize } },
  });

  if (loading) {
    return <TableSkeleton />;
  }

  const visible = table.getRowModel().rows;
  const filtered = table.getFilteredRowModel().rows.length;
  const total = rows?.length ?? 0;

  return (
    <div className="space-y-3">
      {(searchable || exportUrl) && (
        <div className="flex flex-wrap items-center gap-2">
          {searchable && (
            <div className="relative flex-1 sm:max-w-xs">
              <Search
                className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted"
                aria-hidden
              />
              <Input
                label=""
                className="pl-9"
                placeholder={searchPlaceholder}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                aria-label={searchPlaceholder}
              />
            </div>
          )}

          {exportUrl && (
            <Button
              variant="secondary"
              size="sm"
              className="ml-auto"
              pending={exporting}
              onClick={async () => {
                setExporting(true);

                try {
                  await downloadExcel(exportUrl, exportFilename);
                } catch {
                  toast.error("The export failed.");
                } finally {
                  setExporting(false);
                }
              }}
            >
              <Download />
              Export
            </Button>
          )}
        </div>
      )}

      <div className="overflow-hidden rounded-lg border border-subtle bg-surface">
        {/* The table scrolls sideways rather than the page. A page that scrolls horizontally on a
            laptop because one column is wide is how a grid becomes unusable. */}
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="border-b border-subtle bg-surface-sunken">
              {table.getHeaderGroups().map((group) => (
                <tr key={group.id}>
                  {group.headers.map((header) => {
                    const sortable = header.column.getCanSort();
                    const sorted = header.column.getIsSorted();

                    return (
                      <th
                        key={header.id}
                        scope="col"
                        aria-sort={
                          sorted === "asc"
                            ? "ascending"
                            : sorted === "desc"
                              ? "descending"
                              : undefined
                        }
                        className="px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wide text-muted"
                      >
                        {sortable ? (
                          <button
                            type="button"
                            onClick={header.column.getToggleSortingHandler()}
                            className="inline-flex items-center gap-1 transition-colors duration-150 hover:text-text"
                          >
                            {flexRender(header.column.columnDef.header, header.getContext())}

                            {sorted === "asc" && <ArrowUp className="size-3" aria-hidden />}
                            {sorted === "desc" && <ArrowDown className="size-3" aria-hidden />}
                          </button>
                        ) : (
                          flexRender(header.column.columnDef.header, header.getContext())
                        )}
                      </th>
                    );
                  })}
                </tr>
              ))}
            </thead>

            <tbody>
              {visible.map((row, index) => (
                <tr
                  key={row.id}
                  onClick={onRowClick ? () => onRowClick(row.original) : undefined}
                  style={{ animationDelay: `${Math.min(index, 8) * 20}ms` }}
                  className={cn(
                    "animate-in fade-in-0 fill-mode-backwards border-b border-subtle duration-300 last:border-0",
                    "transition-colors",
                    // Every row lifts a touch on hover so the eye can track across a wide grid of
                    // figures; a clickable row lifts more and shows it is clickable.
                    onRowClick ? "cursor-pointer hover:bg-surface-sunken" : "hover:bg-surface-sunken/50",
                  )}
                >
                  {row.getVisibleCells().map((cell) => (
                    <td key={cell.id} className="px-4 py-3 text-text">
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Three different nothings, and they mean different things. "No results for 'kandy'" tells
            the user to change their search; "no customers yet" tells them to add one. Showing the
            same blank box for both is how people conclude the app is broken. */}
        {visible.length === 0 && (
          <div className="flex flex-col items-center gap-2 px-6 py-14 text-center">
            <span className="grid size-10 place-items-center rounded-full bg-surface-sunken text-muted">
              <Inbox className="size-5" aria-hidden />
            </span>

            {query ? (
              <>
                <p className="text-sm font-medium text-text">No results for “{query}”</p>
                <Button variant="ghost" size="sm" onClick={() => setQuery("")}>
                  Clear the search
                </Button>
              </>
            ) : (
              <>
                <p className="text-sm font-medium text-text">{empty?.title ?? "Nothing here yet"}</p>
                {empty?.description && (
                  <p className="max-w-sm text-sm text-muted">{empty.description}</p>
                )}
                {empty?.action}
              </>
            )}
          </div>
        )}
      </div>

      {table.getPageCount() > 1 && (
        <div className="flex items-center justify-between gap-3">
          <p className="text-sm text-muted">
            {filtered === total ? (
              <>
                <span className="tabular font-medium text-text">{total}</span> row
                {total === 1 ? "" : "s"}
              </>
            ) : (
              <>
                <span className="tabular font-medium text-text">{filtered}</span> of{" "}
                <span className="tabular">{total}</span>
              </>
            )}
          </p>

          <div className="flex items-center gap-1">
            <Button
              variant="secondary"
              size="sm"
              disabled={!table.getCanPreviousPage()}
              onClick={() => table.previousPage()}
              aria-label="Previous page"
            >
              <ChevronLeft />
            </Button>

            <span className="tabular px-2 text-sm text-muted">
              {table.getState().pagination.pageIndex + 1} / {table.getPageCount()}
            </span>

            <Button
              variant="secondary"
              size="sm"
              disabled={!table.getCanNextPage()}
              onClick={() => table.nextPage()}
              aria-label="Next page"
            >
              <ChevronRight />
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

function TableSkeleton() {
  return (
    <div className="space-y-3">
      <Skeleton className="h-9 w-full sm:max-w-xs" />

      <div className="overflow-hidden rounded-lg border border-subtle">
        <div className="border-b border-subtle bg-surface-sunken px-4 py-3">
          <Skeleton className="h-3 w-32" />
        </div>

        {[0, 1, 2, 3, 4].map((i) => (
          <div key={i} className="border-b border-subtle px-4 py-3.5 last:border-0">
            <Skeleton className="h-4" style={{ width: `${70 - i * 8}%` }} />
          </div>
        ))}
      </div>
    </div>
  );
}
