import { API_BASE_URL, getActiveCompany } from "@/lib/api";

/**
 * Downloads a real .xlsx workbook, generated by the server.
 *
 * <b>Server-side, and deliberately.</b> The server already holds these values as `decimal` and
 * `DateTime`; ClosedXML writes them into the workbook as numeric cells with a format. Rebuilding a
 * spreadsheet in the browser from JSON would mean a second implementation of "what is a number",
 * working from strings it had re-parsed in whatever locale the user's machine happens to run — and a
 * money column that lands in Excel as *text* cannot be summed. The first thing anyone does with an
 * exported list of invoices is total it.
 *
 * (It also keeps a browser spreadsheet library out of the dependency tree. The obvious one, SheetJS,
 * was pulled from the npm registry and has a history of prototype-pollution advisories.)
 */
export async function downloadExcel(path: string, filename: string): Promise<void> {
  const company = getActiveCompany();

  const response = await fetch(`${API_BASE_URL}${path}`, {
    // The auth cookie is httpOnly, so it has to be asked for explicitly — and the export is a
    // permissioned, audited endpoint like any other.
    credentials: "include",
    headers: company === null ? {} : { "X-Company-Id": String(company) },
  });

  if (!response.ok) {
    throw new Error("The export failed.");
  }

  const blob = await response.blob();
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = filename;
  anchor.click();

  URL.revokeObjectURL(url);
}

/**
 * A client-side CSV of what is on screen.
 *
 * Kept for the lists that have no server export — a filtered subset the user assembled themselves,
 * which the server has never seen. It is NOT the Excel export: it has no formats, no column widths
 * and no typed cells.
 */
export function exportCsv<T>(
  filename: string,
  columns: { header: string; value: (row: T) => unknown }[],
  rows: T[],
) {
  const lines = [
    columns.map((c) => escape(c.header)).join(","),
    ...rows.map((row) => columns.map((c) => escape(c.value(row))).join(",")),
  ];

  // A BOM. Without it Excel opens a UTF-8 CSV as Windows-1252 and turns "Kandy Engineering (Pvt)
  // Ltd — Colombo" into mojibake, which is the kind of bug that gets reported as "the export is
  // broken" and takes an afternoon to find.
  const blob = new Blob(["﻿" + lines.join("\r\n")], {
    type: "text/csv;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = `${filename}.csv`;
  anchor.click();

  URL.revokeObjectURL(url);
}

function escape(value: unknown): string {
  if (value === null || value === undefined) return "";

  const text = String(value);

  // A leading =, +, - or @ makes Excel treat the cell as a FORMULA. A customer named "=cmd|..." is
  // CSV injection, and it executes on the machine of whoever opens the export. Prefix it so the
  // cell is read as text.
  const safe = /^[=+\-@\t\r]/.test(text) ? `'${text}` : text;

  return /[",\r\n]/.test(safe) ? `"${safe.replace(/"/g, '""')}"` : safe;
}
